//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace configControlWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("configControlWpf.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Html Text.
        /// </summary>
        public static string btnGetHtmlText {
            get {
                return ResourceManager.GetString("btnGetHtmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string btnOkText {
            get {
                return ResourceManager.GetString("btnOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string btnTestText {
            get {
                return ResourceManager.GetString("btnTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string cbfiles {
            get {
                return ResourceManager.GetString("cbfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is auto growth url.
        /// </summary>
        public static string cbIsautogrowthurl {
            get {
                return ResourceManager.GetString("cbIsautogrowthurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigate.
        /// </summary>
        public static string cbnexts {
            get {
                return ResourceManager.GetString("cbnexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paths.
        /// </summary>
        public static string cbpaths {
            get {
                return ResourceManager.GetString("cbpaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page config files.
        /// </summary>
        public static string fdFileType {
            get {
                return ResourceManager.GetString("fdFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add After.
        /// </summary>
        public static string tbAddAfter {
            get {
                return ResourceManager.GetString("tbAddAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Before.
        /// </summary>
        public static string tbAddBefore {
            get {
                return ResourceManager.GetString("tbAddBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Growth Par.
        /// </summary>
        public static string tbAutoGrowthPar {
            get {
                return ResourceManager.GetString("tbAutoGrowthPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Exist.
        /// </summary>
        public static string tbCheckExist {
            get {
                return ResourceManager.GetString("tbCheckExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        public static string tbCoding {
            get {
                return ResourceManager.GetString("tbCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string tbEnd {
            get {
                return ResourceManager.GetString("tbEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Config ID.
        /// </summary>
        public static string tbPageConfigID {
            get {
                return ResourceManager.GetString("tbPageConfigID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string tbReplace {
            get {
                return ResourceManager.GetString("tbReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string tbStart {
            get {
                return ResourceManager.GetString("tbStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found  {0} items: .
        /// </summary>
        public static string testMsgFoundItems {
            get {
                return ResourceManager.GetString("testMsgFoundItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found string: .
        /// </summary>
        public static string testMsgFoundString {
            get {
                return ResourceManager.GetString("testMsgFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input url and click &apos;Get Html Text&apos; button.
        /// </summary>
        public static string testMsgInit {
            get {
                return ResourceManager.GetString("testMsgInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test done..
        /// </summary>
        public static string testMsgTestdone {
            get {
                return ResourceManager.GetString("testMsgTestdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test error: .
        /// </summary>
        public static string testMsgTestError {
            get {
                return ResourceManager.GetString("testMsgTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test fail..
        /// </summary>
        public static string testMsgTestfail {
            get {
                return ResourceManager.GetString("testMsgTestfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        public static string testMsgTesting {
            get {
                return ResourceManager.GetString("testMsgTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Handle.
        /// </summary>
        public static string tiFinalHandle {
            get {
                return ResourceManager.GetString("tiFinalHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Text.
        /// </summary>
        public static string tihHtmlText {
            get {
                return ResourceManager.GetString("tihHtmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Model .
        /// </summary>
        public static string tihPageModel {
            get {
                return ResourceManager.GetString("tihPageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string tihSearch {
            get {
                return ResourceManager.GetString("tihSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string tihTest {
            get {
                return ResourceManager.GetString("tihTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Layers.
        /// </summary>
        public static string tiSearchLayers {
            get {
                return ResourceManager.GetString("tiSearchLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Page Model.
        /// </summary>
        public static string titleSelectPageModelID {
            get {
                return ResourceManager.GetString("titleSelectPageModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Page config.
        /// </summary>
        public static string ttbtnAddPage {
            get {
                return ResourceManager.GetString("ttbtnAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Replace item.
        /// </summary>
        public static string ttbtnAddReplace {
            get {
                return ResourceManager.GetString("ttbtnAddReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Search.
        /// </summary>
        public static string ttbtnAddSearch {
            get {
                return ResourceManager.GetString("ttbtnAddSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Search layer.
        /// </summary>
        public static string ttBtnAddSl {
            get {
                return ResourceManager.GetString("ttBtnAddSl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current Page config create a new  config.
        /// </summary>
        public static string ttbtnCopyPage {
            get {
                return ResourceManager.GetString("ttbtnCopyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a search layer.
        /// </summary>
        public static string ttbtnDel {
            get {
                return ResourceManager.GetString("ttbtnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current Page.
        /// </summary>
        public static string ttbtnDelPage {
            get {
                return ResourceManager.GetString("ttbtnDelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current replace item.
        /// </summary>
        public static string ttbtnDelReplace {
            get {
                return ResourceManager.GetString("ttbtnDelReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del current search.
        /// </summary>
        public static string ttbtnDelSearch {
            get {
                return ResourceManager.GetString("ttbtnDelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import config.
        /// </summary>
        public static string ttbtnImport {
            get {
                return ResourceManager.GetString("ttbtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a config file.
        /// </summary>
        public static string ttbtnOpen {
            get {
                return ResourceManager.GetString("ttbtnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save config file.
        /// </summary>
        public static string ttbtnSave {
            get {
                return ResourceManager.GetString("ttbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save config file As....
        /// </summary>
        public static string ttbtnSaveAs {
            get {
                return ResourceManager.GetString("ttbtnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle show/hide Test panel.
        /// </summary>
        public static string ttbtnTest {
            get {
                return ResourceManager.GetString("ttbtnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the search will return multiple results. If unchecked, the search will return only the first result..
        /// </summary>
        public static string ttcbSearchMultiResults {
            get {
                return ResourceManager.GetString("ttcbSearchMultiResults", resourceCulture);
            }
        }
    }
}
