//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xy.scraper.xyWebScraper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xy.scraper.xyWebScraper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BreakpointsWindow {
            get {
                object obj = ResourceManager.GetObject("BreakpointsWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Blank_Gray_icon {
            get {
                object obj = ResourceManager.GetObject("Button-Blank-Gray-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Blank_Green_icon {
            get {
                object obj = ResourceManager.GetObject("Button-Blank-Green-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Blank_Red_icon {
            get {
                object obj = ResourceManager.GetObject("Button-Blank-Red-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Blank_Yellow_icon {
            get {
                object obj = ResourceManager.GetObject("Button-Blank-Yellow-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConfigureComputer {
            get {
                object obj = ResourceManager.GetObject("ConfigureComputer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Log {
            get {
                object obj = ResourceManager.GetObject("Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end scraping by cancel: .
        /// </summary>
        internal static string log_cancel {
            get {
                return ResourceManager.GetString("log_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end scraping successfully.
        /// </summary>
        internal static string log_endSuccessfully {
            get {
                return ResourceManager.GetString("log_endSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end scraping by error: .
        /// </summary>
        internal static string log_error {
            get {
                return ResourceManager.GetString("log_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume breakpoint scraping....
        /// </summary>
        internal static string log_resumeBreakpoint {
            get {
                return ResourceManager.GetString("log_resumeBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start scraping....
        /// </summary>
        internal static string log_startScrape {
            get {
                return ResourceManager.GetString("log_startScrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string msg_fail {
            get {
                return ResourceManager.GetString("msg_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No break point.
        /// </summary>
        internal static string msg_Nobreakpoint {
            get {
                return ResourceManager.GetString("msg_Nobreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no page model configed.
        /// </summary>
        internal static string msg_NoPageModel {
            get {
                return ResourceManager.GetString("msg_NoPageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed.
        /// </summary>
        internal static string msg_succeed {
            get {
                return ResourceManager.GetString("msg_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartWebSite {
            get {
                object obj = ResourceManager.GetObject("StartWebSite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xyWebScraper.
        /// </summary>
        internal static string text_AppName {
            get {
                return ResourceManager.GetString("text_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page: .
        /// </summary>
        internal static string text_lbCurrentPage {
            get {
                return ResourceManager.GetString("text_lbCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files count: .
        /// </summary>
        internal static string text_lbFilesCount {
            get {
                return ResourceManager.GetString("text_lbFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page tasks: .
        /// </summary>
        internal static string text_lbPageTask {
            get {
                return ResourceManager.GetString("text_lbPageTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select PageModel.
        /// </summary>
        internal static string toolTipText_cbConfigIdList {
            get {
                return ResourceManager.GetString("toolTipText_cbConfigIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume breakpoint scrape.
        /// </summary>
        internal static string toolTipText_tbBreakPoint {
            get {
                return ResourceManager.GetString("toolTipText_tbBreakPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show/hide scraping log.
        /// </summary>
        internal static string toolTipText_tbLog {
            get {
                return ResourceManager.GetString("toolTipText_tbLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set page models.
        /// </summary>
        internal static string toolTipText_tbSetting {
            get {
                return ResourceManager.GetString("toolTipText_tbSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select page model, and input page url to active this button.
        /// </summary>
        internal static string toolTipText_tbStart {
            get {
                return ResourceManager.GetString("toolTipText_tbStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start scrape.
        /// </summary>
        internal static string toolTipText_tbStart_active {
            get {
                return ResourceManager.GetString("toolTipText_tbStart_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping, push to cancel scrap.
        /// </summary>
        internal static string toolTipText_tbStart_scraping {
            get {
                return ResourceManager.GetString("toolTipText_tbStart_scraping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waitting for canceled....
        /// </summary>
        internal static string toolTipText_tbStart_waitingCancel {
            get {
                return ResourceManager.GetString("toolTipText_tbStart_waitingCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input Url.
        /// </summary>
        internal static string toolTipText_txtUrl {
            get {
                return ResourceManager.GetString("toolTipText_txtUrl", resourceCulture);
            }
        }
    }
}
