//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xy.scraper.page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xy.scraper.page.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be download break point files: .
        /// </summary>
        internal static string BreakPointFiles {
            get {
                return ResourceManager.GetString("BreakPointFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break point files done
        ///.
        /// </summary>
        internal static string BreakPointFilesDone {
            get {
                return ResourceManager.GetString("BreakPointFilesDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be download break point tasks: .
        /// </summary>
        internal static string BreakPointTasks {
            get {
                return ResourceManager.GetString("BreakPointTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel task, start save break point ....
        /// </summary>
        internal static string CancelTaskStartSaveBreakPoint {
            get {
                return ResourceManager.GetString("CancelTaskStartSaveBreakPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string ExceptionInfo {
            get {
                return ResourceManager.GetString("ExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: .
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried many times and gave up: .
        /// </summary>
        internal static string GaveUpTry {
            get {
                return ResourceManager.GetString("GaveUpTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get task html: .
        /// </summary>
        internal static string GetTaskHtml {
            get {
                return ResourceManager.GetString("GetTaskHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to got download items:.
        /// </summary>
        internal static string GotDownloadItems {
            get {
                return ResourceManager.GetString("GotDownloadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to got other page links: .
        /// </summary>
        internal static string GotOtherPageLinks {
            get {
                return ResourceManager.GetString("GotOtherPageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry: .
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start resume break point ....
        /// </summary>
        internal static string StartResumeBreakPoint {
            get {
                return ResourceManager.GetString("StartResumeBreakPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed: .
        /// </summary>
        internal static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be done: .
        /// </summary>
        internal static string ToBeDone {
            get {
                return ResourceManager.GetString("ToBeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI is invalid..
        /// </summary>
        internal static string URIIsInvalid {
            get {
                return ResourceManager.GetString("URIIsInvalid", resourceCulture);
            }
        }
    }
}
